# Site settings
title: Lambduhh!
email: lambduhh@domain.com
description: > 
  My blog
url: "http://vadali.github.io/" # the base hostname & protocol for your site
highlight: pygments
twitter_username: jekyllrb
github_username:  vadali
baseurl: /blog
# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/
