#+STARTUP: showall
#+STARTUP: hidestars
#+OPTIONS: H:2 num:nil tags:nil toc:nil timestamps:t
#+LAYOUT: post
#+AUTHOR: vadali
#+DATE: 2015-08-06 Thu 03:39
#+TITLE: Java 8 on Amazon EMR
#+DESCRIPTION: a bootstrap action for amazon EMR that installs java 8
#+TAGS: java8,EMR,bootsrap action
#+CATEGORIES: Hadoop

#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="css/orgmode.css"/>

Recently I needed to use a library requiring java 8 on a large hadoop
cluster running on Amazon EMR. I couldn't find any AMI's that has it
installed. After some searching around, I found the gollowing [[https://gist.github.com/ericeijkelenboom/9951500][emr
bootstrap on gist]], which is a yum based solution. Since I use debian
based ami, I modified it slightly, as shown below.

On emr ami, some applications uses java 7, while others uses
java 6. In order to not mess things up, we would like that only our
hadoop job will use java 8. To get that we need to set up =JAVA_HOME=
in the right context, which is to place it under
=/home/hadoop/conf/hadoop-user-env.sh=.

Since we would like to use a ppa to install java 8, take a look at [[https://vadali.github.io/blog/devops/2015/08/05/standalone-add-apt-repository.html][this post]].

In order to use this bootstrap action, simply paste this file
somewhere on your s3 bucket, and make sure to register the full s3 url
of this file as a bootsrap action to your cluster.

#+Caption: java8-bootstrap-action.sh:
#+BEGIN_SRC sh :exports code
  # Check java version
  JAVA_VER=$(java -version 2>&1 | sed 's/java version "\(.*\)\.\(.*\)\..*"/\1\2/; 1q')

  if [ "$JAVA_VER" -lt 18 ]
  then
      echo "Getting add-apt-repository"
      wget --no-check-certificate --no-cookies "https://blog.anantshri.info/content/uploads/2010/09/add-apt-repository.sh.txt" -O add-apt-repository.sh

      echo "Adding oracle java ppa"
      sudo sh add-apt-repository.sh ppa:webupd8team/java

      echo "updating"
      sudo apt-get update

      echo "Setting up installation..."
      echo "oracle-java8-installer shared/accepted-oracle-license-v1-1 select true" | sudo debconf-set-selections

      echo "Installing..."
      sudo apt-get install -y oracle-java8-installer

      echo "Setting JAVA_HOME to java 8"
      echo 'export JAVA_HOME=/usr/lib/jvm/java-8-oracle' > /home/hadoop/conf/hadoop-user-env.sh
  fi

  # Check java version again
  JAVA_VER=$(java -version 2>&1 | sed 's/java version "\(.*\)\.\(.*\)\..*"/\1\2/; 1q')

  echo ""
  echo "Java version is $JAVA_VER!"
  echo "JAVA_HOME: $JAVA_HOME"
  echo "JRE_HOME: $JRE_HOME"
  echo "PATH: $PATH"
#+END_SRC
